name:                xmonad-config
version:             0.1.0.0
github:              "rinse/xmonad-config"
license:             BSD3
author:              "rinse"
maintainer:          "rinse@neko2.net"
copyright:           "2019 rinse"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rinse/xmonad-config#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- xmonad >= 0.17
- xmonad-contrib >= 0.17
- microlens
- microlens-mtl
- mtl

library:
  source-dirs: lib

executables:
  xmonad-config:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config

tests:
  xmonad-config-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config
    - hspec >= 2.7.0
    - containers

  doctest:
    main:                Spec.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config
    - doctest >= 0.16
    - QuickCheck >= 2.13
